"""
硬件在环实验脚本

截取Tiny LLaMA模型第一层的真实Query、Key、Value，将其量化为INT8格式，输出为C代码头文件

同时实际运行前向传播，获得模型标准困惑度

待C读取头文件、运行Chipyard Int Flash Attention后，读取C端输出结果，注入模型第一层的Attention输出，继续前向传播，获得实际困惑度

TODO: 该测试脚本目前仅支持最初的FP32 Softmax精度，暂不支持FP16 Softmax
"""
import torch
from pathlib import Path
from golden.flash_attention import to_c_array
from typing import Callable, Tuple, Optional
from transformers.modeling_utils import ALL_ATTENTION_FUNCTIONS
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.models.llama.modeling_llama import (
    LlamaAttention,
    apply_rotary_pos_emb,
    repeat_kv,
    eager_attention_forward,
)

BR = 128
BC = 256
SEED = 42
MODE = "NORMAL"

def write_c_head(Q_int8: torch.Tensor,
                 K_int8: torch.Tensor,
                 V_int8: torch.Tensor,
                 S_q: torch.Tensor,
                 S_k: torch.Tensor,
                 S_v: torch.Tensor,
                 seq_len: int,
                 head_dim: int,
                 num_heads: int,
                 batch_size: int,
                 br: int = BR,
                 bc: int = BC) -> None:
    target_header_path = Path("./bareMetalC/llama_data.h")

    with target_header_path.open("w", encoding="utf-8") as f:
        f.write(f"#ifndef LLAMA_DATA_H\n#define LLAMA_DATA_H\n\n")
        f.write(f"// Generated by Python script. \n// SEQ_LEN = {seq_len}, BR = {br}, BC = {bc}, HEAD_DIM = {head_dim}, NUM_HEADS = {num_heads}, BATCH_SIZE = {batch_size}\n")
        f.write(f"// The arrays have been flattened already.\n")
        f.write(f"#include \"include/gemmini_params.h\"\n\n")

        f.write(f"#define SEQ_LEN {seq_len}\n")
        f.write(f"#define BR {br}\n")
        f.write(f"#define BC {bc}\n")
        f.write(f"#define HEAD_DIM {head_dim}\n")
        f.write(f"#define NUM_HEADS {num_heads}\n")
        f.write(f"#define BATCH_SIZE {batch_size}\n\n")

        f.write(to_c_array(tensor=Q_int8, name="Q_int8_gen", type_str="elem_t") + "\n")
        f.write(to_c_array(tensor=K_int8, name="K_int8_gen", type_str="elem_t") + "\n")
        f.write(to_c_array(tensor=V_int8, name="V_int8_gen", type_str="elem_t") + "\n")
        f.write(to_c_array(tensor=S_q, name="S_q_gen", type_str="float") + "\n")
        f.write(to_c_array(tensor=S_k, name="S_k_gen", type_str="float") + "\n")
        f.write(to_c_array(tensor=S_v, name="S_v_gen", type_str="float") + "\n")

        f.write("\n#endif\n")

def init_int8_attention_data(seq_len: int,
                             head_dim: int,
                             query: Optional[torch.Tensor] = None,
                             key: Optional[torch.Tensor] = None,
                             value: Optional[torch.Tensor] = None,
                             seed: int = SEED,
                             is_random: bool = True) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    为Attention Forward初始化随机/给定INT8 Q, K, V张量及其缩放因子
    
    :param query: 可选的查询张量，如果为None则随机生成
    :type query: Optional[torch.Tensor]
    :param key: 可选的键张量，如果为None则随机生成
    :type key: Optional[torch.Tensor]
    :param value: 可选的值张量，如果为None则随机生成
    :type value: Optional[torch.Tensor]
    :param seed: 种子
    :type seed: int
    :param seq_len: 序列长度
    :type seq_len: int
    :param head_dim: 头部维度
    :type head_dim: int
    :param is_random: 是否随机生成数据，如果为False则使用给定的query, key, value张量
    :type is_random: bool
    :return: 初始化的Q, K, V张量及其缩放因子，若为随机生成，则不包含Batch与Head维度，否则与输入张量维度一致
    :rtype: Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]
    """
    if is_random:
        if seed is not None:
            torch.manual_seed(seed)
        Q_float32 = torch.randn(size=(seq_len, head_dim), dtype=torch.float32)
        K_float32 = torch.randn(size=(seq_len, head_dim), dtype=torch.float32)
        V_float32 = torch.randn(size=(seq_len, head_dim), dtype=torch.float32)
    else:
        assert query is not None and key is not None and value is not None, "When is_random is False, query, key, value must be provided."
        Q_float32 = query.float()
        K_float32 = key.float()
        V_float32 = value.float()

    S_q = torch.max(torch.abs(Q_float32), dim=-1).values / 127.0
    S_k = torch.max(torch.abs(K_float32), dim=-1).values / 127.0
    S_v = torch.max(torch.max(torch.abs(V_float32), dim=-1).values, dim=-1).values / 127.0

    Q_int8 = torch.clamp((Q_float32 / S_q.unsqueeze(-1)), -128, 127).to(torch.int8)
    K_int8 = torch.clamp((K_float32 / S_k.unsqueeze(-1)), -128, 127).to(torch.int8)
    V_int8 = torch.clamp((V_float32 / S_v.unsqueeze(-1).unsqueeze(-1)), -128, 127).to(torch.int8)

    return Q_int8, K_int8, V_int8, S_q, S_k, S_v

def export_llama_attention_data(query: torch.Tensor,
                                key: torch.Tensor,
                                value: torch.Tensor,
                                seq_len: int,
                                head_dim: int,
                                num_heads: int,
                                batch_size: int,
                                br: int = BR,
                                bc: int = BC,
                                seed: int = SEED) -> None:
    Q_int8, K_int8, V_int8, S_q, S_k, S_v = init_int8_attention_data(query=query,
                                                                     key=key,
                                                                     value=value,
                                                                     seed=seed,
                                                                     seq_len=seq_len,
                                                                     head_dim=head_dim,
                                                                     is_random=False)
    write_c_head(Q_int8=Q_int8,
                 K_int8=K_int8,
                 V_int8=V_int8,
                 S_q=S_q,
                 S_k=S_k,
                 S_v=S_v,
                 seq_len=seq_len,
                 head_dim=head_dim,
                 num_heads=num_heads,
                 batch_size=batch_size,
                 br=br,
                 bc=bc)
    
def inject_c_output(output_path: Path,
                    seq_len: int,
                    head_dim: int,
                    num_heads: int,
                    batch_size: int,) -> torch.Tensor:
    O_c = torch.tensor([])

    # 定义 C 代码中打印数据的锚点字符串 (根据 flash_attn_on_riscv_npu.c)
    ANCHOR_STR = "The outputs of shape" 
    
    if output_path.is_file():
        with output_path.open("r", encoding="utf-8") as f:
            lines = f.readlines()
            for idx, line in enumerate(lines):
                if ANCHOR_STR in line:
                    if idx + 1 < len(lines):
                        data_line = lines[idx + 1]
                        values = [float(x) for x in data_line.strip().split()]
                        expected_len = batch_size * num_heads * seq_len * head_dim
                        if len(values) != expected_len:
                            print(f"[Warning] Log数据长度 ({len(values)}) 与预期 ({expected_len}) 不符，请检查Log文件完整性。")
                        
                        O_c = torch.tensor(values, dtype=torch.float32).reshape(batch_size, num_heads, seq_len, head_dim)
                        return O_c
    else:
        raise FileNotFoundError(f"{output_path}文件不存在。")
    
    if O_c.numel() == 0:
        raise ValueError(f"未能从{output_path}中解析出有效数据，请检查C仿真是否成功运行并生成了Log。")

    return O_c

def custom_forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],
        attention_mask: Optional[torch.Tensor],
        past_key_values = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """
        用于硬件验证的自定义Forward，只修改第一层
        """
        if self.layer_idx != 0:
             return LlamaAttention.original_forward(    # type: ignore[attr-defined]
                  self,
                  hidden_states,
                  position_embeddings,
                  attention_mask,
                  past_key_values,
                  cache_position,
                  **kwargs
             )
        
        input_shape = hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)

        query_states = self.q_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        key_states = self.k_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(hidden_shape).transpose(1, 2)

        cos, sin = position_embeddings
        query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)

        if past_key_values is not None:
            # sin and cos are specific to RoPE models; cache_position needed for the static cache
            cache_kwargs = {"sin": sin, "cos": cos, "cache_position": cache_position}
            key_states, value_states = past_key_values.update(key_states, value_states, self.layer_idx, cache_kwargs)

        attention_interface: Callable = eager_attention_forward
        if self.config._attn_implementation != "eager":
            attention_interface = ALL_ATTENTION_FUNCTIONS[self.config._attn_implementation]

        global MODE

        if MODE == "DUMP":
            print(f"[Hook] 正在导出 Layer {self.layer_idx} 的 Q/K/V...")

            export_llama_attention_data(query=query_states,
                                        key=repeat_kv(key_states, self.num_key_value_groups),
                                        value=repeat_kv(value_states, self.num_key_value_groups),
                                        seq_len=query_states.shape[2],
                                        head_dim=query_states.shape[3],
                                        num_heads=query_states.shape[1],
                                        batch_size=query_states.shape[0],
                                        br=BR,
                                        bc=BC,
                                        seed=SEED)
            print(f"[Hook] 已导出 Layer {self.layer_idx} 的 Q/K/V 到 ./source/llama_data.h, 继续执行原始前向计算...")

            attn_output, attn_weights = attention_interface(
                self,
                query_states,
                key_states,
                value_states,
                attention_mask,
                dropout=0.0 if not self.training else self.attention_dropout,
                scaling=self.scaling,
                **kwargs,
            )

            attn_output = attn_output.reshape(*input_shape, -1).contiguous()
            attn_output = self.o_proj(attn_output)
            
        elif MODE == "INJECT":
            print(f"[Hook] 正在注入 Layer {self.layer_idx} 的 C 代码计算结果...")

            attn_output = inject_c_output(Path(r"\\wsl.localhost\Ubuntu-Chipyard\home\yenxu\chipyard\sims\verilator\output\chipyard.harness.TestHarness.GemminiRocketSaturnConfig\llama_out.log"),
                                          seq_len=query_states.shape[2],
                                          head_dim=query_states.shape[3],
                                          num_heads=query_states.shape[1],
                                          batch_size=query_states.shape[0]).to(query_states.device)
            attn_output = attn_output.transpose(1, 2).contiguous()

            attn_output_duplicate, attn_weights = attention_interface(
                self,
                query_states,
                key_states,
                value_states,
                attention_mask,
                dropout=0.0 if not self.training else self.attention_dropout,
                scaling=self.scaling,
                **kwargs,
            )

            attn_output = attn_output.reshape(*input_shape, -1).contiguous()
            attn_output = self.o_proj(attn_output)
            print(f"[Hook] 已注入 Layer {self.layer_idx} 的C代码计算结果，继续执行后续计算...")
            
        else:
            attn_output, attn_weights = attention_interface(
                self,
                query_states,
                key_states,
                value_states,
                attention_mask,
                dropout=0.0 if not self.training else self.attention_dropout,
                scaling=self.scaling,
                **kwargs,
            )

            attn_output = attn_output.reshape(*input_shape, -1).contiguous()
            attn_output = self.o_proj(attn_output)

        return attn_output, attn_weights

if __name__ == "__main__":
    if not hasattr(LlamaAttention, "original_forward"):
        setattr(LlamaAttention, "original_forward", LlamaAttention.forward)

    DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    MODE = "NORMAL"

    model = AutoModelForCausalLM.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0").to(DEVICE)   # type: ignore[call-arg]
    tokenizer = AutoTokenizer.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0")

    text = "多年以后，面对行刑队，奥雷里亚诺·布恩迪亚上校将会回想起父亲带他去见识冰块的那个遥远的下午。那时的马孔多是一个二十户人家的村落，泥巴和芦苇盖成的屋子沿河岸排开，湍急的河水清澈见底，河床里卵石洁白光滑宛如史前巨蛋。世界新生伊始，许多事物还没有名字，提到的时候尚需用手指指点点。"
    input_ids = tokenizer(text, return_tensors="pt").input_ids.to(DEVICE)
    labels = input_ids.clone()
    print(f"Int Flash Attention LlaMA Evaluation Starts...")
    print(f"Input Text: \"{text}\", Sequence Length: {input_ids.shape[1]}")

    LlamaAttention.forward = custom_forward

    # === DUMP 模式 ===
    MODE = "DUMP"
    print(f"\n>>> Running {MODE} Mode")
    
    with torch.no_grad():
        outputs_golden = model(input_ids=input_ids, labels=labels)
        loss_golden = outputs_golden.loss
        ppl_golden = torch.exp(loss_golden)

    print(f"原始前向传播结束，Golden PPL: {ppl_golden.item():.4f}, Golden Loss: {loss_golden.item():.4f}")
    input("\n>>> 请运行 C 代码仿真，生成 log 文件后，再按任意键运行 INJECT 模式")

    # === INJECT 模式 ===
    MODE = "INJECT"
    print(f"\n>>> Running {MODE} Mode")
    with torch.no_grad():
       outputs_c = model(input_ids=input_ids, labels=labels)
       loss_c = outputs_c.loss
       ppl_c = torch.exp(loss_c)
    
    print(f"Hardware (Simulated) PPL: {ppl_c.item():.4f}, Hardware (Simulated) Loss: {loss_c.item():.4f}")
    print(f"PPL Difference: {abs(ppl_c.item() - ppl_golden.item()):.4f}")
    print("\n>>> Evaluation finished. Please check the PPL difference and analyze any discrepancies.")
