"""
将C端单头Flash Attention Forward的输出与Pytorch标准实现进行对比验证的脚本
得到相关误差指标并输出为纯文本文件
"""
import torch
import torch.nn.functional as F
from flash_attention_forward_single_head_eval import flash_attention_forward_single_head
from flash_attention_forward_inner_eval import to_c_array
from typing import Tuple
from pathlib import Path

SEQ_LEN = 1024
HEAD_DIM = 64
BR = 128
BC = 256
SEED = 42

def init_int8_attention_data(seed: int = SEED,
                             seq_len: int = SEQ_LEN,
                             head_dim: int = HEAD_DIM) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    为Attention Forward初始化随机INT8 Q, K, V张量及其缩放因子
    
    :param seed: 种子
    :type seed: int
    :param seq_len: 序列长度
    :type seq_len: int
    :param head_dim: 头部维度
    :type head_dim: int
    :return: 初始化的Q, K, V张量及其缩放因子，形状分别为(Q, K, V): (seq_len, head_dim), (seq_len, head_dim), (seq_len, head_dim); 缩放因子(S_q, S_k, S_v): (seq_len,), (seq_len,), scalar
    :rtype: Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]
    """
    if seed is not None:
        torch.manual_seed(seed)
    
    Q_float32 = torch.randn(size=(seq_len, head_dim), dtype=torch.float32)
    K_float32 = torch.randn(size=(seq_len, head_dim), dtype=torch.float32)
    V_float32 = torch.randn(size=(seq_len, head_dim), dtype=torch.float32)

    S_q = torch.max(torch.abs(Q_float32), dim=1).values / 127.0
    S_k = torch.max(torch.abs(K_float32), dim=1).values / 127.0
    S_v = torch.max(torch.abs(V_float32)) / 127.0

    Q_int8 = torch.clamp((Q_float32 / S_q.unsqueeze(1)), -128, 127).to(torch.int8)
    K_int8 = torch.clamp((K_float32 / S_k.unsqueeze(1)), -128, 127).to(torch.int8)
    V_int8 = torch.clamp((V_float32 / S_v), -128, 127).to(torch.int8)

    return Q_int8, K_int8, V_int8, S_q, S_k, S_v

def attention_fp32_single_head_golden(Q_int8: torch.Tensor,
                                      K_int8: torch.Tensor,
                                      V_int8: torch.Tensor,
                                      S_q: torch.Tensor,
                                      S_k: torch.Tensor,
                                      S_v: torch.Tensor,
                                      seed: int = SEED) -> torch.Tensor:
    """
    采用标准Pytorch Scaled Dot Product Attention实现Attention模块，接受输入INT8类型的Query, Key, Value并将其反量化为FP32后进行计算
    
    用于与C代码INT8 Flash Attention相比较

    :param Q_int8: INT8 Query of shape (SEQ_LEN, HEAD_DIM)
    :type Q_int8: torch.Tensor
    :param K_int8: INT8 Key of shape (SEQ_LEN, HEAD_DIM)
    :type K_int8: torch.Tensor
    :param V_int8: INT8 Value of shape (SEQ_LEN, HEAD_DIM)
    :type V_int8: torch.Tensor
    :param S_q: FP32 Token level scaler for Query of shape (SEQ_LEN, )
    :type S_q: torch.Tensor
    :param S_k: FP32 Token level scaler for Key of shape (SEQ_LEN, )
    :type S_k: torch.Tensor
    :param S_v: FP32 Tensor level scaler for Value
    :type S_v: torch.Tensor
    :param seed: Seed
    :type seed: int
    :return: FP32 Output tensor of shape (SEQ_LEN, HEAD_DIM)
    :rtype: torch.Tensor
    """
    if seed is not None:
        torch.manual_seed(seed)

    Q_fp32 = Q_int8.to(torch.float32) * S_q.unsqueeze(1)
    K_fp32 = K_int8.to(torch.float32) * S_k.unsqueeze(1)
    V_fp32 = V_int8.to(torch.float32) * S_v

    O_fp32 = F.scaled_dot_product_attention(query = Q_fp32.unsqueeze(0).unsqueeze(0), # 增加 Batch 和 Head 维度
                                            key = K_fp32.unsqueeze(0).unsqueeze(0),
                                            value = V_fp32.unsqueeze(0).unsqueeze(0),
                                            is_causal = True).squeeze(0).squeeze(0) # 去掉 Batch 和 Head 维度
    
    return O_fp32

def write_c_head(Q_int8: torch.Tensor,
                 K_int8: torch.Tensor,
                 V_int8: torch.Tensor,
                 S_q: torch.Tensor,
                 S_k: torch.Tensor,
                 S_v: torch.Tensor):
    with open("./source/random_data.h", "w") as f:
        f.write(f"#ifndef RANDOM_DATA_H\n#define RANDOM_DATA_H\n\n")
        f.write(f"// Generated by Python script. \n// SEQ_LEN = {SEQ_LEN}, BR = {BR}, BC = {BC}, HEAD_DIM = {HEAD_DIM}, SEED = {SEED}\n")
        f.write(f"// The arrays have been flattened already.\n")
        f.write(f"#include \"include/gemmini_params.h\"\n\n")

        f.write(f"#define SEQ_LEN {SEQ_LEN}\n")
        f.write(f"#define BR {BR}\n")
        f.write(f"#define BC {BC}\n")
        f.write(f"#define HEAD_DIM {HEAD_DIM}\n\n")

        f.write(to_c_array(tensor=Q_int8, name="Q_int8_gen", type_str="elem_t") + "\n")
        f.write(to_c_array(tensor=K_int8, name="K_int8_gen", type_str="elem_t") + "\n")
        f.write(to_c_array(tensor=V_int8, name="V_int8_gen", type_str="elem_t") + "\n")
        f.write(to_c_array(tensor=S_q, name="S_q_gen", type_str="float") + "\n")
        f.write(to_c_array(tensor=S_k, name="S_k_gen", type_str="float") + "\n")
        f.write(f"static float S_v_gen = {S_v.item()}f;\n")

        f.write("\n#endif\n")

if __name__ == "__main__":
    print("The evaluation of flash_attention_forward_single_head starts...")

    # Calculation & Read the C output
    Q_int8, K_int8, V_int8, S_q, S_k, S_v = init_int8_attention_data()

    # Write C header file                
    write_c_head(Q_int8, K_int8, V_int8, S_q, S_k, S_v)

    O_golden = attention_fp32_single_head_golden(Q_int8, K_int8, V_int8, S_q, S_k, S_v)
    O_python = flash_attention_forward_single_head(Q_int8, K_int8, V_int8, S_q, S_k, S_v, seq_len=SEQ_LEN, is_causal=True)
    O_c = torch.tensor([])

    # path2c_output = Path(r"\\wsl.localhost\Ubuntu-Chipyard\home\yenxu\chipyard\sims\verilator\output\chipyard.harness.TestHarness.GemminiRocketSaturnConfig\flash_attn_on_riscv_npu-baremetal.log")

    # if path2c_output.is_file():
    #     with path2c_output.open("r", encoding="utf-8") as f:
    #         for i, line in enumerate(f, start=1):
    #             if i == 19:
    #                 values = [float(x) for x in line.strip().split()]
    #                 O_c = torch.tensor(values, dtype=torch.float32).reshape(SEQ_LEN, HEAD_DIM)
    #                 break

    # Write output comparison files
    # Path("./analysis/data/single_head_outputs/").mkdir(parents=True, exist_ok=True)

    # with open(f"./analysis/data/single_head_outputs/O_golden_seq{SEQ_LEN}_brbc{BR}x{BC}.txt", "w") as f:
    #     for row in O_golden:
    #         f.write(" ".join([f"{x:.6f}" for x in row]) + "\n\n")

    # with open(f"./analysis/data/single_head_outputs/O_python_seq{SEQ_LEN}_brbc{BR}x{BC}.txt", "w") as f:
    #     for row in O_python:
    #         f.write(" ".join([f"{x:.6f}" for x in row]) + "\n\n")
    
    # with open(f"./analysis/data/single_head_outputs/O_c_seq{SEQ_LEN}_brbc{BR}x{BC}.txt", "w") as f:
    #     for row in O_c:
    #         f.write(" ".join([f"{x:.6f}" for x in row]) + "\n\n")

    print(f"Successfully generated \"./source/random_data.h\"(parameters: SEQ_LEN={SEQ_LEN}, BR={BR}, BC={BC}, HEAD_DIM={HEAD_DIM}, SEED={SEED}), and runs the PyTorch golden model, outputs are in ./analysis/data/single_head_outputs/ file.")